import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import vm from 'node:vm';

const vendor = readFileSync(new URL('../js/vendor/lunar-javascript/lunar.js', import.meta.url), 'utf8');
const moduleSource = readFileSync(new URL('../js/meeow-special-dates.js', import.meta.url), 'utf8');
const html = readFileSync(new URL('../index.html', import.meta.url), 'utf8');
const sandbox = { console };
sandbox.window = sandbox;
vm.createContext(sandbox);
vm.runInContext(vendor, sandbox, { filename: 'lunar.js' });
vm.runInContext(moduleSource, sandbox, { filename: 'meeow-special-dates.js' });
const dates = sandbox.Meeow.specialDates;
const atNoon = (year, month, day) => new Date(year, month - 1, day, 12);
const ids = state => Array.from(state.holidays, holiday => holiday.id);
const solarRules = dates.RULES.filter(rule => rule.calendar === 'gregorian');
const lunarRules = dates.RULES.filter(rule => rule.calendar === 'lunar' && !rule.computed);
assert.equal(dates.RULES.length, 21);
assert.equal(solarRules.length, 10);
assert.equal(lunarRules.length, 10);
assert.equal(dates.evaluate(atNoon(2026, 3, 12)).holidays.length, 0);
for (const rule of solarRules) {
    const state = dates.evaluate(atNoon(2026, rule.month, rule.day));
    assert.ok(ids(state).includes(rule.id), `Gregorian ${rule.id}`);
    assert.equal(state.lunar.available, true);
}
for (const rule of lunarRules) {
    const solar = sandbox.Lunar.fromYmd(2026, rule.month, rule.day).getSolar();
    assert.ok(ids(dates.evaluate(atNoon(solar.getYear(), solar.getMonth(), solar.getDay()))).includes(rule.id), `Lunar ${rule.id}`);
}
const midAutumn = dates.evaluate(atNoon(2026, 9, 25));
assert.equal(midAutumn.dateKey, '2026-09-25');
assert.deepEqual(ids(midAutumn), ['mid-autumn']);
assert.equal(midAutumn.holidays[0].greeting, '中秋节快乐');
assert.throws(() => { midAutumn.holidays[0].id = 'invented-holiday'; }, TypeError);
const lunarNewYear = sandbox.Lunar.fromYmd(2027, 1, 1).getSolar();
const eve = new Date(lunarNewYear.getYear(), lunarNewYear.getMonth() - 1, lunarNewYear.getDay() - 1, 12);
assert.ok(ids(dates.evaluate(eve)).includes('lunar-new-years-eve'));
const leap = dates.evaluate(atNoon(2026, 9, 25), () => ({ getMonth: () => -8, getDay: () => 15 }));
assert.ok(!ids(leap).includes('mid-autumn'));
const coincident = dates.evaluate(atNoon(2026, 12, 25), () => ({ getMonth: () => 8, getDay: () => 15 }));
assert.deepEqual(ids(coincident), ['christmas', 'mid-autumn']);
assert.equal(coincident.primaryHolidayId, 'mid-autumn');
const failed = dates.evaluate(atNoon(2026, 12, 25), () => { throw new Error('simulated'); });
assert.deepEqual(ids(failed), ['christmas']);
assert.equal(failed.lunar.available, false);
assert.equal(failed.lunar.errorCode, 'lunar-conversion-failed');
const unavailable = dates.evaluate(atNoon(2026, 12, 25), null);
assert.deepEqual(ids(unavailable), ['christmas']);
assert.equal(unavailable.lunar.errorCode, 'lunar-library-unavailable');
assert.equal(dates.getInteractionHolidayContext(dates.evaluate(atNoon(2026, 3, 12))), '');
assert.match(dates.getInteractionHolidayContext(midAutumn), /"id":"mid-autumn"/);
assert.match(dates.getInteractionHolidayContext(coincident), /"id":"christmas".*"id":"mid-autumn"/);
assert.doesNotMatch(dates.getInteractionHolidayContext(midAutumn), /lunarError|lunar-library|fromDate/);
const oldTimezone = process.env.TZ;
try {
    process.env.TZ = 'America/Los_Angeles';
    const beforeMidnight = new Date('2026-09-26T06:59:59.000Z');
    const afterMidnight = new Date('2026-09-26T07:00:00.000Z');
    assert.equal(dates.evaluate(beforeMidnight).dateKey, '2026-09-25');
    assert.ok(ids(dates.evaluate(beforeMidnight)).includes('mid-autumn'));
    assert.equal(dates.evaluate(afterMidnight).dateKey, '2026-09-26');
    assert.ok(!ids(dates.evaluate(afterMidnight)).includes('mid-autumn'));
    assert.ok(dates.nextLocalMidnightDelay(beforeMidnight) < 2000);
} finally {
    if (oldTimezone === undefined) delete process.env.TZ;
    else process.env.TZ = oldTimezone;
}
const seen = [];
const unsubscribe = dates.subscribe(state => seen.push(state.dateKey));
dates.refresh(atNoon(2026, 9, 25));
assert.equal(dates.hasHoliday('mid-autumn'), true);
assert.deepEqual(Array.from(dates.getCurrentHolidayIds()), ['mid-autumn']);
dates.refresh(atNoon(2026, 9, 26));
assert.equal(dates.isHolidayActive(), false);
assert.deepEqual(seen.slice(-2), ['2026-09-25', '2026-09-26']);
unsubscribe();
const phoneStart = html.indexOf('                const buildPhoneReplyGenerationTask =');
const phoneEnd = html.indexOf('                const stablePhoneReplyNumber =', phoneStart);
assert.ok(phoneStart >= 0 && phoneEnd > phoneStart);
sandbox.getCanonicalCatId = id => id;
sandbox.getInteractionHolidayContext = () => dates.getInteractionHolidayContext();
sandbox.buildResidentConversationKnowledgeContext = () => ({ prompt: '' });
sandbox.formatFrozenPhoneReplyThread = () => '';
vm.runInContext(`${html.slice(phoneStart, phoneEnd)}\nglobalThis.buildPhoneTask = buildPhoneReplyGenerationTask;`, sandbox);
const phoneOpportunity = { contactId: 'bruce', knowledgeScopeFrozen: true, phoneHallName: 'Meeow House' };
dates.refresh(atNoon(2026, 3, 12));
assert.doesNotMatch(sandbox.buildPhoneTask(phoneOpportunity, 'Bruce'), /AUTHORITATIVE HOLIDAY CONTEXT/);
dates.refresh(atNoon(2026, 9, 25));
assert.match(sandbox.buildPhoneTask(phoneOpportunity, 'Bruce'), /"id":"mid-autumn"/);
dates.refresh(atNoon(2026, 12, 25));
assert.match(sandbox.buildPhoneTask(phoneOpportunity, 'Bruce'), /"id":"christmas"/);
const sidecar = sandbox.buildPhoneTask(phoneOpportunity, 'Bruce', dates.getInteractionHolidayContext(midAutumn));
assert.match(sidecar, /"id":"mid-autumn"/);
assert.doesNotMatch(sidecar, /\[CURRENT USER ACTION\]/);
assert.match(html, /src="\.\/js\/vendor\/lunar-javascript\/lunar\.js"/);
assert.match(html, /src="\.\/js\/meeow-special-dates\.js"/);
assert.doesNotMatch(html, /cdn\.jsdelivr\.net\/npm\/lunar-javascript/);
assert.match(html, /v-if="holidayState\.holidays\.length"/);
assert.match(html, /meeow-holiday-banner/);
const bannerMarkup = html.slice(html.indexOf('<section v-if="holidayState.holidays.length"'), html.indexOf('<!-- Alfred Voice Card -->'));
assert.match(bannerMarkup, /holiday\.name/);
assert.doesNotMatch(bannerMarkup, /alfredMessage/);
assert.match(html, /scheduleHolidayMidnightRefresh\(\)/);
assert.match(html, /document\.addEventListener\('visibilitychange'/);
assert.match(html, /window\.addEventListener\('focus', refreshHolidayOnFocus\)/);
assert.match(html, /OPERATIONAL_DAY_START_HOUR = 3/);
assert.doesNotMatch(moduleSource, /OPERATIONAL_DAY_START_HOUR|toISOString\(\)\.slice/);
assert.match(html, /buildPhoneReplyGenerationTask\(claimedPhoneOpportunity, getResidentPublicName\(sendingCat\), interactionHolidayContext\)/);
assert.match(html, /const prompt = buildPhoneReplyGenerationTask\(opportunity, contact\.name\)/);
assert.match(html, /\$\{holidayContext\}\\n\[PHONE RESIDENT SNAPSHOT\]/);
assert.match(html, /\[CURRENT AUTHORITATIVE STATE\]\n\$\{foreground\.currentState\}\n\$\{interactionHolidayContext\}/);
assert.match(html, /const sharedHolidayContext = getInteractionHolidayContext\(\)/);
assert.match(html, /getDateContext\(null, \{ includeHoliday: false \}\)/);
assert.equal((html.match(/callAI\(/g) || []).length + (readFileSync(new URL('../js/meeow-ai.js', import.meta.url), 'utf8').match(/callAI\(/g) || []).length, 40);
console.log('special-date-holiday-authority-v1: PASS (21 rules, offline lunar, local midnight, refresh, Hall, channels)');
